[package]
name = "microtensor"
version = "0.1.1"
edition = "2021"
description = "Automatic differentiation for tensor operations"
authors = ["Björn Breitgoff <syntheticore@gmail.com>"]
keywords = ["autograd", "tensor", "ml"]
categories = ["mathematics", "science"]
license = "MIT"
homepage = "https://crates.io/crates/microtensor"
repository = "https://github.com/syntheticore/microtensor"
readme = "README.md"

[dependencies]
rand = "0.7.3"
num-traits = "0.2.15"
serde = { version = "1.0.145", features = ["derive", "rc"] }
serde_traitobject = { version = "0.2.8", git = "https://github.com/syntheticore/serde_traitobject" }
postcard = { version = "1.0.2", features = ["alloc"] }
matrixmultiply = "0.3.2"

rayon = { version = "1.5.3", optional = true }

[features]
default = ["rayon"]
rayon = ["dep:rayon"]

[profile.dev]
opt-level = 3

[profile.release]
lto = 'fat'
codegen-units = 1
